---
title: "Final Fundamentos 2023"
output: html_document
---

Un reporte con las respuestas se deberá enviar por correo electrónico a más 
tardar el martes 5 a las 21:00 horas.

Instrucciones: 

- En las siguientes preguntas describe tus procedimientos y escribe las
respuestas explícitamente (que no haya necesidad de correr código para 
obtenerlas). 

- Incluye el código.

- No está permitido discutir el exámen fuera de su equipo.

- Para dudas (que no deben incluir info. de la respuesta) se preguntará en el 
canvas del grupo.

- Consideren el material de visualización al hacer sus gráficas y reportar sus
resultados.

## 1. Pruebas de hipótesis

1.1 De acuerdo a una encuesta en EUA, 26% de los residentes adultos de Illinois han 
terminado la preparatoria. Un investigador sospecha que este porcentaje es
menor en un condado particular del estado. Obtiene una muestra aleatoria de 
dicho condado y encuentra que 69 de 310 personas en la muestra han completado
la preparatoria. Estos resultados soportan su hipótesis? (describe tu elección de
prueba de hipótesis, valor p y conclusión).



1.2 Mendel criaba chícharos de semillas lisas amarillas y de semillas
corrugadas verdes. Éstas daban lugar a 4 tipos de descendientes: amarrillas lisas, amarillas corrugadas, verdes lisas y verdes corrugadas. El número de cada una
es multinomial con parámetro $p=(p_1, p_2, p_3, p_4)$. De acuerdo a su teoría de
herencia este vector de probabilidades es:
$$p=(9/16,3/16,3/16,1/16)$$
A lo largo de $n=556$ experimentos observó $x=(315,101,108,32)$. Utiliza la prueba
de cociente de verosimilitudes para probar $H_0:p=p_0$ contra $H_0:p\ne p_0$.



1.3. Sean $X_1, ...X_n \sim Poisson(\lambda)$,

* Sea $\lambda_0>0$. ¿Cuál es la prueba Wald para
$H_0: \lambda = \lambda_0, H_1: \lambda \neq \lambda_0$

* Si $\lambda_0=1$, $n=20$ y $\alpha = 0.05$. Simula  $X_1, ...X_n \sim Poisson(\lambda_0)$ y realiza la prueba Wald, repite 1000 veces y registra
el porcentaje de veces que rechazas $H_0$, qué tan cerca te queda el
error del tipo 1 de $0.05$?

